In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [3]:
print(np.zeros((2,3))) # it will create a matrix of two rows and three columns all values zero

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
print(np.ones((2,3))) # it will create a matrix of two rows and three columns all values one

[[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
print(np.full((2,3), 7)) # 2 rows and 3 columns all values will be 7

[[7 7 7]
 [7 7 7]]


In [7]:
print(np.arange(0, 10, 2)) # print from 0 to 10  and step size is 2, 0 will be included and 10 will not be included

[0 2 4 6 8]


In [8]:
print(np.linspace(0, 1, 5)) # it mean print from 0 to 1 and give me 5 parts

[0.   0.25 0.5  0.75 1.  ]


In [9]:
print(np.eye(3)) # Identity matrix of 3 rows and 3 columns

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
print(np.diag([1,2,3])) # Diagnal values will be 1, 2, 3 and non-diagonal values will be 0

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [11]:
np.array([1,2,3], dtype=float) # datatyep will be float see result is 1., 2., 3.

array([1., 2., 3.])

In [12]:
arr = np.array([1.5, 2.7, 3.9])
print(arr.astype(int)) # it mean print as integer

[1 2 3]
