In [1]:
import numpy as np

In [2]:
arr = np.array([[10,20,30],
               [40,50,60],
               [70,80,90]])

In [3]:
print(arr[0,1]) # 20 (row 0 and column 1)
print(arr[2,2]) # 90 (row 2 and column 2)

20
90


In [4]:
print(arr[-1, -2]) # 80 (last row and 2nd last column)
print(arr[-3, -3]) # 10 (first row and first column)

80
10


In [5]:
# General form arr[start:stop:step]
print(arr[0:2, 1:3]) # rows 0-1, columns 1-2

[[20 30]
 [50 60]]


In [7]:
print(arr[::2, ::2]) # every 2nd row and 2nd columns 2 rows ka jump lya aur 2 columns ka jump lya

[[10 30]
 [70 90]]


In [7]:
slice_arr = arr[0, :2] # view(not a copy) 
slice_arr[0] = 999

In [8]:
print(arr[0]) # original changes

[999  20  30]


In [9]:
copy_arr = arr[1].copy() # independent copy
copy_arr[0] = 555

In [13]:
print(arr[1]) # original unchnaged

[40 50 60]


In [ ]:
# random generator with seed (reproductibility)
rng = np.random.default_rng(seed=42)
nums = rng.integers(1, 10, size=5)